### ISSUE TITLE
sort words with frequency

### ISSUE THREAD

**Issue by iknite** [vermicida/palabros#2]
Using the rae frequency corpus it will increase the quality of the dataset? 

https://en.wiktionary.org/wiki/Wiktionary:Frequency_lists#Spanish

**Comment by vermicida** [comment]
Of course, I will check this dataset. Frequency is not the only aspect that matters, but definitely it's an important one; it enable most of the people to enjoy the game, since the proposed seed words are familiar to them.

That's the first task I will take to improve the game. Thank you for the advice & link :-)

**Comment by vermicida** [comment]
Done! I've rebuilt the dictionary from scratch using the 3.750 most common words from the RAE's link you shared. Thanks @iknite 😊
